import type { Metadata } from "next";
import { Inter, Space_Grotesk, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/src/presentation/layout/navbar/Navbar";
import SiteProvider from "@/src/presentation/providers/SiteProvider";
import Footer from "@/src/presentation/layout/footer/Footer";
import { Suspense } from "react";
import StorageSync from "@/src/presentation/controllers/StorageSync";
import { NuqsAdapter } from "nuqs/adapters/next/app";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${spaceGrotesk.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <NuqsAdapter>
          <SiteProvider>
            <Suspense fallback={null}>
              <StorageSync />
            </Suspense>

            <Navbar />
            <main className="grow rounded-md py-5">{children}</main>
            <Footer />
          </SiteProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
