import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_layout/navbar/Navbar";
import SiteProvider from "./_providers/SiteProvider";
import Footer from "./_layout/footer/Footer";
import { Suspense } from "react";
import StorageSync from "./_controllers/StorageSync";
import { NuqsAdapter } from "nuqs/adapters/next/app";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <NuqsAdapter>
          <SiteProvider>
            <Suspense fallback={null}>
              <StorageSync />
            </Suspense>

            <Navbar />
            <main className="grow rounded-md py-5 items-center flex">{children}</main>
            <Footer />
          </SiteProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
